terms:
  - id: Abstract
    term: Abstract
  - id: Methods
    term: Methods
  - id: SeriesInformation
    term: Series Information
  - id: TableOfContents
    term: Table Of Contents
  - id: TechnicalInfo
    term: Technical Info
  - id: description
    term: Description
  - id: 
  - id: Other
    term: Other
 